name: flutter_link_previewer
description: >
  URL preview extracted from the provided text with
  basic customization and ability to render from cached data.
version: 2.2.3
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types:
    git: 
      url: https://github.com/ebb-flow-group/flutter_chat_types
      ref: voice_message
  flutter_linkify: ^5.0.2
  html: ^0.15.0
  http: ^0.13.1
  linkify: ^4.1.0
  meta: ^1.7.0
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
